add_newline = false

format = '''
$time $username $directory $fill $all
$character
'''
[time]
disabled = false
format = '[\[$time\]]($style)'
style = 'bold cyan'

[username]
disabled = false
show_always = true
format = '[$user]($style)'
style_user = 'bold green'
style_root = 'bold red'

[directory]
truncation_symbol = '../'
format = '[$path/]($style)[$read_only]($read_only_style)'
read_only = ''
style = 'bold yellow'
read_only_style = 'blink red'

[character]
success_symbol = '[](bold white)'
error_symbol = '[](bold red)'
format = '$symbol'

[git_branch]
always_show_remote = true
symbol = ' '
format = '[$symbol\($branch\) ]($style)'
style = 'white'

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[nodejs]
format = '[$symbol]($style)'
style = 'red'

[lua]
symbol = ' '
format = '[$symbol]($style)'
style = 'blue'

[cmd_duration]
disabled = true
