add_newline = false

format = '''
$time $username $directory \$ 
'''

right_format = '''
$git_branch $nodejs $lua
'''

[time]
disabled = false
format = '[\[$time\]]($style)'
style = 'bold cyan'

[username]
disabled = false
show_always = true
format = '[$user]($style)'
style_user = 'bold green'
style_root = 'bold red'

[directory]
truncation_symbol = '../'
format = '[$path/]($style)[ $read_only]($read_only_style)'
# TODO: should use a nerd symbol of some kind
read_only = ''
style = 'bold yellow'
read_only_style = 'blink red'

[git_branch]
always_show_remote = true
symbol = ' '
format = '[$symbol\($branch\)]($style)'
style = 'green'

[nodejs]
format = '[$symbol]($style)'
style = 'red'

[lua]
symbol = ' '
format = '[$symbol]($style)'
style = 'blue'
